services:
  slurmctld:
    build: 
      context: .
      dockerfile: services/slurm.Dockerfile
    command: ["slurmctld"]
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./services/:/etc/slurm/
    expose:
      - "6817"
      - "22"
    ports:
      - 6817:6817
    networks:
      - cluster
      - virtual_machine

  node:
    build: 
      context: .
      dockerfile: services/slurm.Dockerfile
    command: ["slurmd"]
    hostname: node
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./services/:/etc/slurm/
    expose:
      - "6818"
    depends_on:
      - slurmctld
    networks:
      - cluster

  mongo:
    image: mongo:4.4
    env_file: ".env"
    networks:
      - virtual_machine

  open-box:
    build:
      context: .
      dockerfile: services/open-box.Dockerfile
    depends_on:
      - mongo
    ports:
      - 8000:8000
    expose:
      - "8000"
    networks:
      - virtual_machine
      - cluster

  postgres:
    image: postgres
    env_file: ".env"
    networks:
      - virtual_machine

  orchestrator:
    build:
      context: .
      dockerfile: services/orchestrator.Dockerfile
    volumes:
      - orchestrator_app:/app
    ports:
      - 8080:8080
    expose:
      - "8080"
    depends_on:
      - postgres
      - open-box
      - slurmctld
    networks:
      - virtual_machine

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./
  var_log_slurm:
  orchestrator_app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./ 
  pg_migrations:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./

networks:
  virtual_machine:
    driver: bridge
