[project]
name = "buckpass"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8, <3.12"
dependencies = [
    "requests>=2.32.4",
]

[dependency-groups]
dev = []

[tool.pyright]
venvPath = "../../"
venv = ".venv"
reportMissingTypeStubs = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
